version: '3'

networks:
  backend:
    driver: bridge

services:
  nginx-php:
    container_name: nginx-php
#    network_mode: host
    networks:
      - backend
    privileged: true
    image: nginx:1.18.0
    environment:
      TZ: Asia/Shanghai
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/nginx/logs/nginx.logs:/var/log/nginx
      - /work/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm-platform-api
      - php-fpm-platform-swoole
      - platform-vue-admin

  platform-vue-admin:
    container_name: platform-vue-admin
#    network_mode: host
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-vue-admin
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9528:9528"
    expose:
      - 9528
    stdin_open: true
    tty: true
    volumes:
      - /work/www:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html/platform-vue-admin
    command: npm install && npm run dev

  php-fpm-platform-api:
    container_name: php-fpm-platform-api
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    # expose暴露容器给link到当前容器的容器
    environment:
      TZ: Asia/Shanghai
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
    working_dir: /usr/share/nginx/html/platform
    depends_on:
      - redis-php

  php-fpm-platform-swoole:
    container_name: php-fpm-platform-swoole
#    network_mode: host
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    environment:
      TZ: Asia/Shanghai
    expose:
      - 5200
    ports:
      - "5200:5200"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - /work/compose/laravels.sh:/laravels.sh
    working_dir: /usr/share/nginx/html/platform
    entrypoint: sh /laravels.sh
    depends_on:
      - redis-php

  redis-php:
    container_name: redis-php
#    network_mode: host
    networks:
      - backend
    privileged: true
    image: redis:6.0.2
    environment:
      TZ: Asia/Shanghai
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - /work/redis/data:/data
      - /work/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
