version: '3'

networks:
  backend:
    driver: bridge

services:
  nginx:
    container_name: nginx
    networks:
      - backend
    privileged: true
    image: nginx:1.18.0
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/nginx/logs/nginx.logs:/var/log/nginx
      - /work/nginx/conf.d:/etc/nginx/conf.d

  php-fpm-platform:
    container_name: php-fpm-platform
    image: image-php-fpm-platform
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    # expose暴露容器给link到当前容器的容器
    expose:
      - 9000
    ports:
      - "9000:9000"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
    working_dir: /usr/share/nginx/html/platform

  php-fpm-platform-swoole:
    container_name: php-fpm-platform-swoole
    image: image-php-fpm-platform-swoole
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    expose:
      - 5200
    # 绑定容器的9000端口到主机的9999端口  9999:9000
    ports:
      - "5200:5200"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - /work/compose/laravels.sh:/laravels.sh
    working_dir: /usr/share/nginx/html/platform
    entrypoint: sh /laravels.sh

  php-fpm-platform-horizon:
    container_name: php-fpm-platform-horizon
    image: image-php-fpm-platform-horizon
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    expose:
      - 5200
    # 绑定容器的9000端口到主机的9999端口  9999:9000
    ports:
      - "6200:5200"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - /work/compose/laravels.sh:/laravels.sh
    working_dir: /usr/share/nginx/html/platform
    entrypoint: sh /laravels.sh

  php-fpm-platform-doc:
    container_name: php-fpm-platform-doc
    image: image-php-fpm-platform-doc
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    expose:
      - 5200
    # 绑定容器的9000端口到主机的9999端口  9999:9000
    ports:
      - "7200:5200"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - /work/compose/laravels.sh:/laravels.sh
    working_dir: /usr/share/nginx/html/platform
    entrypoint: sh /laravels.sh

  php-fpm-platform-telescope:
    container_name: php-fpm-platform-telescope
    image: image-php-fpm-platform-telescope
    networks:
      - backend
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile-php
    # image: php:7.4.6-fpm
    expose:
      - 5200
    # 绑定容器的9000端口到主机的9999端口  9999:9000
    ports:
      - "8200:5200"
    volumes:
      - /work/www:/usr/share/nginx/html
      - /work/php/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /work/php/etc/php/php.ini-production:/usr/local/etc/php/php.ini-production
      - /work/php/etc/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - /work/compose/laravels.sh:/laravels.sh
    working_dir: /usr/share/nginx/html/platform
    entrypoint: sh /laravels.sh

  redis:
    container_name: redis
    networks:
      - backend
    privileged: true
    image: redis:6.0.2
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - /work/redis/data:/data
      - /work/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
